version: '3.7'

services:

  planner:
    image: planner-dev
    container_name: planner-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app:delegated'
      - '/app/node_modules'
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true