version: '3.7'

services:

  planner-prod:
    image: planner
    container_name: planner
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443



      